version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_tracker_kanban
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql --username=postgres --dbname=task_tracker_kanban -c 'SELECT 1;'"]
      interval: 10s
      timeout: 5s
      retries: 3
