version: '3.8'


services:
  db:
    container_name: db
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "task_tracker_kanban"
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    image: backend:0.1.0
    restart: always
    ports:
    - "8000:8000"
    environment:
      HOST_1: "0.0.0.0"
      PORT_1: 8000
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/task_tracker_kanban
    depends_on:
      - db
      
  frontend:
    container_name: frontend
    image: frontend:0.1.0
    restart: always
    ports:
    - "3000:3000"
    environment:
      SOCKET_BACKEND: "backend:8000"
